<?php
$customerList = $this->getData('customers');
$customerID = $this->getData('customerID');
$customerName = $this->getData('customerName');
?>

<?php include(BASE_DIR . '/templates/head.phtml') ?>

    Ma view List Customers
    <ul>

        <?php foreach ($customerList as $customer) : ?>
            <li><b><?= $customer->getnom() ?>  <?= $customer->getprenom() ?> - </b>  <?= $customer->getAddress() ?></li>
        <?php endforeach; ?>
    </ul>

<?php if ($customerID != null) : ?>
    <b><?= $customerID->getnom() ?>  <?= $customerID->getprenom() ?> - </b>  <?= $customerID->getAddress() ?><br>
<?php endif; ?>

<?php if ($customerName != null) : ?>
    <b><?= $customerName->getnom() ?>  <?= $customerName->getprenom() ?> - </b>  <?= $customerName->getAddress() ?>
<?php endif; ?>

<?php include(BASE_DIR . '/templates/footer.phtml') ?>