<?php
$todoList = $this->getData('todolist');
?>

<?php include(BASE_DIR . '/templates/head.phtml') ?>

    Ma To Do List

    <ul>
        <?php foreach ($todoList as $todo) : ?>
            <li>
                <p>Utilisateur n° : <?= $todo['userId'] ?></p>
                <p>N° de la tâche : <?= $todo['id'] ?></p>
                <p>Nom de la tâche : <?= $todo['title'] ?></p>
                <p>Statut : <?= $todo['completed'] == 'true' ? 'Faite' : 'Pas encore faite' ?></p>
            </li>
        <?php endforeach; ?>
    </ul>

<?php include(BASE_DIR . '/templates/footer.phtml') ?>