<?php
$todoList = $this->getData('todolist');
?>

<?php include(BASE_DIR . '/templates/head.phtml') ?>

    To Do List

    <ul style="display:grid; grid-template-columns: repeat(4, 1fr); grid-gap: 20px; padding-left: 0;">
        <?php foreach ($todoList as $todo) : ?>
            <?php $bgColor = $todo['completed'] == 'true' ? '#2ecc71' : '#e74c3c' ?>
            <li style="background-color: <?= $bgColor ?>; padding: 15px; list-style-type: none;">
                <p>Utilisateur n° : <?= $todo['userId'] ?></p>
                <p>N° de la tâche : <?= $todo['id'] ?></p>
                <p>Nom de la tâche : <?= $todo['title'] ?></p>
                <p>Statut : <?= $todo['completed'] == 'true' ? 'Faite' : 'Pas encore faite' ?></p>
            </li>
        <?php endforeach; ?>
    </ul>

<?php include(BASE_DIR . '/templates/footer.phtml') ?>